Repository Saikat2407/DSA_Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#2 added bfs traversal
  c++/bfs.cpp
Labels: hacktoberfest

#5 Added number_search program
  c++/Numbers_Searching_add.cpp
Labels: Hacktoberfest2023, hacktoberfest-accepted

#8 Added solution vertical-level-order-traversal-of-a-binary-tree
  c++/vertical-order-traversal-of-a-binary-tree.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#7 Added binary search
  c++/binarySearch.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#9 Added solution to Boolean Matrix a GFG problem
  c++/Boolean_matrix.cpp
Labels: hacktoberfest-accepted

#10 Create Reverse Words.cpp
  c++/Reverse Words.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#11 Minimum Size Subarray in Infinite Array Added
  c++/Minimum_Size_Subarray_in_Infinite_Array.cpp
Labels: hacktoberfest-accepted

#20 Added DP codes to enhance the repo programs
  c++/Dynamic Programming/1_Climbing_Stairs.cpp
  c++/Dynamic Programming/1_Fibonacci_Series.cpp
  c++/Dynamic Programming/2_Min_Cost_Climbing_Stairs.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#15 b plus traversal
  c++/bplus.cpp
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#17 Create First-Missing-Positive(Leetcode)
  c++/First-Missing-Positive(Leetcode)
Labels: Hacktoberfest2023, hacktoberfest, hacktoberfest-accepted

#24 UniqueElement C++ code added
  c++/UniqueElement.cpp
Labels: hacktoberfest-accepted

#38 Finding the Longest Increasing Subsequence in c++ #34
  c++/Dynamic Programming/LIS.cpp
Labels: Hacktoberfest2023, hacktoberfest-accepted

#18 Create reverse_word_in_a_string_III.cpp
  c++/reverse_word_in_a_string_III.cpp
Labels: hacktoberfest-accepted

#72 Password generator
  Java
  Java/PasswordCreater.java
Labels: hacktoberfest-accepted

#70 Added number_of_good_pairs in java
  JAVA/HashMap/Number_of_good_pairs.java
  JAVA/Java.txt
Labels: Hacktoberfest2023, hacktoberfest-accepted

#49 LRU Cache Leetcode #146
  Python/LRU Cache.py
Labels: hacktoberfest-accepted

#46 2873 maximum-value-of-an-ordered-triplet-i
  c++/2873. Maximum Value of an Ordered Triplet I/2873. Maximum Value of an Ordered Triplet I.cpp
Labels: hacktoberfest-accepted

#76 Create Game.py
  Python/Game.py
Labels: hacktoberfest-accepted

#44 Added a file in CPP folder
  c++/Search in a Binary Search Tree.cpp
Labels: hacktoberfest-accepted

#73 Good Pairs POTD in cpp
  c++/number_of_good_pairs.cpp
Labels: hacktoberfest-accepted

#98 Create TowerOfHanoi.java
  JAVA/TowerOfHanoi.java
Labels: hacktoberfest-accepted

#43 Create Intersection_of_two_LL.cpp
  Intersection_of_two_LL.cpp
Labels: changes required

#197 Added a typing game javascript file
  Javascript/typing_game_js.js
Labels: enhancement, hacktoberfest-accepted

#179 min-max array
  c++/max-array.cpp
Labels: hacktoberfest-accepted

#198 Add calculator.py
  Python/calculator.py
Labels: hacktoberfest-accepted

#192 Create Find_the_safe_position.java
  JAVA/Find_the_safe_position.java
Labels: Hacktoberfest2023, hacktoberfest-accepted

#148 Adding JS interview topics
  Javascript/JS_Interview/inde.js
Labels: hacktoberfest-accepted
